#welcome to numpy.

In [20]:
import numpy as np

In [21]:
myarr = np.array([3, 6, 32, 7], np.int32)

In [22]:
myarr[2]

np.int32(32)

In [23]:
myarr.shape

(4,)

In [24]:
myarr.dtype

dtype('int32')

In [25]:
myarr

array([ 3,  6, 32,  7], dtype=int32)

Method 1 to generate an array in numpy


In [26]:
listarray = np.array([[1, 2, 3], [4, 5, 6], [6, 7,8]])

In [27]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [28]:
listarray.dtype

dtype('int64')

In [29]:
listarray.shape

(3, 3)

In [30]:
listarray.size

9

To make a n x m size zero's matrix

In [31]:
zeros = np.zeros((2,5))

In [32]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**To make 0 to n-1 number array**

In [33]:
range = np.arange(15)

In [34]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**it gives elements array in which space between 1 to 5 and elements will be in 12 in number.**

In [35]:
lspace = np.linspace(1,5,12)

In [36]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

**will provide an empty array with random values of given size**

In [37]:
emp = np.empty((4, 6))

In [38]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.37961641e-306,
        9.45697982e-308, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 8.01097889e-307, 1.42417629e-306],
       [8.45593934e-307, 6.89805151e-307, 1.86920057e-306,
        1.11261570e-306, 8.01091099e-307, 6.89807188e-307],
       [1.24611741e-306, 2.22522597e-306, 1.33511969e-306,
        9.45697982e-308, 8.45610231e-307, 2.10081501e-312]])

**To get identity matrix**

In [39]:
ide = np.identity(3)

In [40]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**To get reshaped matrix**

In [41]:
arr = np.arange(99)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

**To get matrix done in original format**

In [44]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])