AXIS in numpy

**Axis can be either in single or in multidimention**
axis 1 --->
   a  1 2 3
   x  4 5 6
   i  7 8 9
   s
   0
   ^
   |


In [2]:
import numpy as np

In [4]:
x = [[1, 2, 3], [4,5, 6], [7, 8, 9]]

In [5]:
ar = np.array(x)

In [6]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
ar.sum(axis = 0)

array([12, 15, 18])

In [8]:
ar.sum(axis=1)

array([ 6, 15, 24])